#ifndef __RobotSpecs_H_
#define __RobotSpecs_H_

#define WHEEL_RADIUS 0.05
#define WTOW_LENGHT 0.20
#define WTO_WIDTH 0.22

#define ENCODERS_COUNTABLE_EVENTS_MOTOR_SHAFT 28
#define ENCODERS_COUNTABLE_EVENTS_OUTPUT_SHAFT 1993.6
#define MOTOR_OUTPUT_SHAFT_MAX_RPM 84
#define MOTOR_GEAR_RATIO 71.2

#define ODOM_RATE 100
#define ODOM_PERIOD 0.01

#define MAX_SPEED 0.44

#define MAX_DELTA_ENCODERS 40 // ((MOTOR_OUTPUT_SHAFT_MAX_RPM / 60) * ENCODERS_COUNTABLE_EVENTS_OUTPUT_SHAFT) * ODOM_PERIOD
#define MAX_DELTA_POSE 0.005 // ((MOTOR_OUTPUT_SHAFT_MAX_RPM / 60) * 2 * M_PI * WHEEL_RADIUS) / ODOM_RATE

#endif