# TrajectoryPlannerROS:
#   max_vel_x: 0.25
#   min_vel_x: 0.05
#   max_vel_theta: 0.5
#   min_in_place_vel_theta: 0.4

#   acc_lim_theta: 3.2
#   acc_lim_x: 1
#   acc_lim_y: 1

#   holonomic_robot: true 

EBandPlannerROS:

  #TRAJECTORY CONTROL
  differential_drive: false
  max_acceleration: 0.4

  virtual_mass : 1.0

  max_translational_acceleration : 0.4
  max_rotational_acceleration : 1.0

  bubble_velocity_multiplier : 0.5

  disallow_hysteresis : false

  # velocity limits
  max_vel_lin: 0.4
  max_vel_th: 1.0
  min_vel_lin: 0.05
  min_vel_th: 0.005
  min_in_place_vel_th: 0.0
  in_place_trans_vel: 0.0

  # goal tolerance
  xy_goal_tolerance: 0.02
  yaw_goal_tolerance: 0.01

  # angular velocity PID
  k_prop : 2.0
  k_damp : 2.0


  num_iterations_eband_optimization : 10




