# TrajectoryPlannerROS:
#   max_vel_x: 0.4
#   min_vel_x: 0.01
#   max_vel_theta: 1.0
#   min_in_place_vel_theta: 0.005

#   acc_lim_theta: 1.0
#   acc_lim_x: 0.8
#   acc_lim_y: 0.8

#   escape_vel: -0.3

#   y_vels: [-0.4,-0.2,-0.1,-0.05,0.05,0.1,0.2,0.4]

#   holonomic_robot: true 

#   # goal tolerance
#   xy_goal_tolerance: 0.05
#   yaw_goal_tolerance: 0.01

# dwa: true

DWAPlannerROS:
  max_trans_vel: 0.4

  max_vel_x: 0.4
  min_vel_x: 0.01

  max_vel_y: 0.4
  min_vel_y: 0.01

  max_rot_vel: 1.0
  min_rot_vel: 0.005

  acc_lim_th: 1.0
  acc_lim_x: 0.8
  acc_lim_y: 0.8

  # goal tolerance
  xy_goal_tolerance: 0.05
  yaw_goal_tolerance: 0.01




