obstacle_range: 10 #updates obstacles at 10m from the robot
raytrace_range: 1
footprint: [[0.3, 0.25], [-0.364, 0.25], [-0.364, -0.25], [0.3, -0.25]]
#robot_radius: ir_of_robot
inflation_radius: 0.15

observation_sources: laser_scan_sensor 

laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}

