#!/usr/bin/env python




MINHEIGHT = 690 #mm
MAXHEIGHT = 1076 #mm

MAXSPEEDTICKS = 1500 #ticks
MAXTICKS = 14558 #ticks

TICKSPERMM = MAXTICKS/(MAXHEIGHT-MINHEIGHT) #ticks for 1 mm
MAXSPEED_M_S = (MAXSPEEDTICKS/TICKSPERMM)*0.001 # m.s-1

ACCELTICKS = 800 #ticks
DECELTICKS = 800 #ticks